name: Fix Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Release version (e.g. 12)"
                required: true

jobs:
    fix:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.event.inputs.version }}
            FIX_ID: ${{ github.run_number }}

        steps:
            - uses: actions/checkout@v3

            - name: Установка Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Установка зависимостей
              run: npm ci

            - name: Проверка типов и тесты
              run: |
                  npm run lint
                  npm run test

            - name: Docker login
              run: echo "${{ secrets.YCR_PASSWORD }}" | docker login --username "${{ secrets.YCR_USERNAME }}" --password-stdin cr.yandex

            - name: Сборка и пуш фикса
              run: |
                  docker build -t cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_fix${FIX_ID} .
                  docker tag cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_fix${FIX_ID} cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_latest
                  docker push cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_fix${FIX_ID}
                  docker push cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_latest

            - name: Тег фикса
              run: |
                  git tag v${VERSION}_fix${FIX_ID}
                  git push origin v${VERSION}_fix${FIX_ID}

            - name: Формирование issue с описанием фикса
              run: |
                  DATE=$(date '+%Y-%m-%d')
                  VERSION="v${{ env.VERSION }}"
                  FIX_ID="${{ env.FIX_ID }}"
                  AUTHOR="${{ github.actor }}"
                  DOCKER_TAG="cr.yandex/${{ secrets.YCR_REGISTRY_ID }}/app:${VERSION}_fix${FIX_ID}"

                  # Определение предыдущего тега
                  PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

                  # Получение списка коммитов
                  if [ -z "$PREV_TAG" ]; then
                    COMMITS=$(git log --pretty=format:'- %h %s')
                  else
                    COMMITS=$(git log --pretty=format:'- %h %s' $PREV_TAG..HEAD)
                  fi

                  # Сборка текста issue
                  {
                    echo "## 🛠 Фикс релиза ${VERSION}_fix${FIX_ID}"
                    echo ""
                    echo "**📅 Дата:** $DATE"
                    echo "**👤 Автор:** $AUTHOR"
                    echo "**🐳 Docker-образ:** \`$DOCKER_TAG\`"
                    echo ""
                    echo "**📄 Коммиты с момента тега \`$PREV_TAG\`:**"
                    echo "$COMMITS"
                  } > fix.md

            - name: Создание Issue о фиксе
              uses: peter-evans/create-issue-from-file@v4
              with:
                  title: "Fix Release ${{ env.VERSION }}_fix${{ env.FIX_ID }}"
                  content-filepath: ./fix.md
